slice_name: Shipments over Time
viz_type: echarts_timeseries_line
datasource_table: shipments
params:
  metrics:
    - expressionType: SQL
      sqlExpression: COUNT(*)
      label: Shipments
      optionName: metric_shipments_time
  x_axis: shipment_date
  granularity_sqla: shipment_date
  time_grain_sqla: P1M
  time_range: No filter
  row_limit: 10000
  show_legend: true
  rich_tooltip: true
