slice_name: Big Number with Trendline  [Default]
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 44__table
  viz_type: big_number
  slice_id: 266
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  x_axis: travel_date
  time_grain_sqla: P1M
  aggregation: LAST_VALUE
  metric:
    aggregate: SUM
    column:
      column_name: cost
      type: FLOAT
    expressionType: SIMPLE
    label: SUM(cost)
    optionName: metric_sum_cost
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: travel_date
  compare_lag: ''
  compare_suffix: ''
  show_timestamp: false
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.4
  subheader_font_size: 0.15
  subtitle_font_size: 0.15
  show_metric_name: false
  metric_name_font_size: 0.15
  show_x_axis: false
  show_x_axis_min_max_labels: false
  show_y_axis: false
  show_y_axis_min_max_labels: false
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  force_timestamp_formatting: false
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 30
query_context: '{"datasource":{"id":44,"type":"table"},"force":false,"queries":[{"filters":[{"col":"travel_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"travel_date","label":"travel_date","expressionType":"SQL","isColumnReference":true}],"metrics":[{"aggregate":"SUM","column":{"column_name":"cost","type":"FLOAT"},"expressionType":"SIMPLE","label":"SUM(cost)","optionName":"metric_sum_cost"}],"annotation_layers":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["travel_date"],"columns":[],"aggregates":{"SUM(cost)":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"44__table","viz_type":"big_number","slice_id":266,"matrixify_enable":false,"matrixify_mode_columns":"disabled","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_all_sort_by_columns":"a_to_z","matrixify_topn_order_columns":true,"matrixify_show_column_headers":true,"matrixify_fit_columns_dynamically":true,"matrixify_mode_rows":"disabled","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_all_sort_by_rows":"a_to_z","matrixify_topn_order_rows":true,"matrixify_show_row_labels":true,"matrixify_row_height":300,"matrixify_charts_per_row":4,"matrixify_cell_title_template":"","x_axis":"travel_date","time_grain_sqla":"P1M","aggregation":"LAST_VALUE","metric":{"aggregate":"SUM","column":{"column_name":"cost","type":"FLOAT"},"expressionType":"SIMPLE","label":"SUM(cost)","optionName":"metric_sum_cost"},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"travel_date"}],"compare_lag":"","compare_suffix":"","show_timestamp":false,"show_trend_line":true,"start_y_axis_at_zero":true,"color_picker":{"a":1,"b":135,"g":122,"r":0},"header_font_size":0.4,"subheader_font_size":0.15,"subtitle_font_size":0.15,"show_metric_name":false,"metric_name_font_size":0.15,"show_x_axis":false,"show_x_axis_min_max_labels":false,"show_y_axis":false,"show_y_axis_min_max_labels":false,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","force_timestamp_formatting":false,"rolling_type":"None","extra_form_data":{},"dashboards":[30],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a8c0f319-a82a-4060-a248-b08e1be68a08
version: 1.0.0
dataset_uuid: a854ddeb-d172-4504-8db5-799864cae3e8
