# Chart name displayed on the dashboard
slice_name: Bar Chart [Default]
# Visualization type (e.g. big_number_total, echarts_timeseries_bar)
viz_type: echarts_timeseries_bar
# Source table/dataset (must exist in datasets/)
datasource_table: tutorial_flights
# Visualization-specific configuration
params:
  viz_type: echarts_timeseries_bar
  slice_id: 279
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  x_axis: travel_date
  time_grain_sqla: P1M
  metrics:
  - aggregate: SUM
    column:
      column_name: cost
      type: FLOAT
    expressionType: SIMPLE
    label: SUM(cost)
    optionName: metric_sum_cost
  groupby:
  - department
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: travel_date
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastEnabled: false
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: ''
  x_axis_title_margin: 0
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: false
  color_scheme: supersetColors
  show_value: false
  minorTicks: false
  zoomable: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  x_axis_number_format: ~g
  xAxisLabelRotation: 0
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateYAxis: false
  y_axis_bounds:
  - 
  - 
  truncateXAxis: true
  force_max_interval: false
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: false
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  echart_options: '{}'
  extra_form_data: {}
  dashboards:
  - 28
