# Chart name displayed on the dashboard
slice_name: deck.gl GeoJson [Default]
# Visualization type (e.g. big_number_total, echarts_timeseries_bar)
viz_type: deck_geojson
# Source table/dataset (must exist in datasets/)
datasource_table: tutorial_flights
# Visualization-specific configuration
params:
  viz_type: deck_geojson
  slice_id: 322
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  geojson: destination_geojson
  row_limit: 1000
  filter_nulls: true
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: travel_date
  tooltip_contents: []
  tooltip_template: ''
  mapbox_style: mapbox://styles/mapbox/light-v9
  viewport:
    bearing: 0
    latitude: 52.6376
    longitude: -1.1351
    pitch: 0
    zoom: 4
  autozoom: true
  fill_color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  stroke_color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  filled: true
  stroked: true
  extruded: false
  enable_labels: false
  enable_label_javascript_mode: false
  label_property_name: name
  label_color:
    a: 1
    b: 0
    g: 0
    r: 0
  label_size: 24
  label_size_unit: pixels
  label_javascript_config_generator: "() => ({\n  // Check the documentation at:\n  // https://deck.gl/docs/api-reference/layers/geojson-layer#pointtype-options-2\n\
    \  getText: f => f.properties.name,\n  getTextColor: [0, 0, 0, 255],\n  getTextSize: 24,\n  textSizeUnits: 'pixels',\n\
    })"
  enable_icons: false
  enable_icon_javascript_mode: false
  icon_url: ''
  icon_size: 32
  icon_size_unit: pixels
  icon_javascript_config_generator: "() => ({\n  // Check the documentation at:\n  // https://deck.gl/docs/api-reference/layers/geojson-layer#pointtype-options-1\n\
    \  getIcon: () => ({ url: '', height: 128, width: 128 }),\n  getIconSize: 32,\n  iconSizeUnits: 'pixels',\n})"
  line_width: 1
  line_width_unit: pixels
  js_columns: []
  js_data_mutator: ''
  js_tooltip: ''
  js_onclick_href: ''
  extra_form_data: {}
  dashboards:
  - 31
