# Chart name displayed on the dashboard
slice_name: Waterfall Chart [Default]
# Visualization type (e.g. big_number_total, echarts_timeseries_bar)
viz_type: waterfall
# Source table/dataset (must exist in datasets/)
datasource_table: tutorial_flights
# Visualization-specific configuration
params:
  viz_type: waterfall
  slice_id: 288
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  x_axis: travel_date
  time_grain_sqla: P1M
  groupby:
  - travel_class
  metric:
    aggregate: SUM
    column:
      column_name: cost
      type: FLOAT
    expressionType: SIMPLE
    label: SUM(cost)
    optionName: metric_sum_cost
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: travel_date
  row_limit: 1000
  show_value: false
  show_legend: false
  increase_color:
    a: 1
    b: 137
    g: 193
    r: 90
  decrease_color:
    a: 1
    b: 85
    g: 67
    r: 224
  show_total: true
  total_color:
    a: 1
    b: 102
    g: 102
    r: 102
  x_axis_label: ''
  x_axis_time_format: smart_date
  x_ticks_layout: auto
  y_axis_label: ''
  y_axis_format: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 28
